[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-protocol-mysql"
version = "0.3.0"

[dependencies]
sqlx-core-guts = { version = "0.6", features = [
    "runtime-tokio-rustls",
    "mysql",
], path = "../../sqlx-core-guts/sqlx-core-guts" }
warpgate-admin = { version = "*", path = "../warpgate-admin" }
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "1.19", features = ["tracing", "signal"] }
tracing = "0.1"
uuid = { version = "0.8", features = ["v4"] }
bytes = "1.1"
mysql_common = "0.29"
rand = "0.8"
sha1 = "0.10.1"
password-hash = { version = "0.2", features = ["std"] }
delegate = "0.6"
rustls = "0.20"
rustls-pemfile = "1.0"
tokio-rustls = "0.23"
thiserror = "1.0"
webpki = "0.22"
webpki-roots = "0.22"
